#!/bin/sh

#########################################################################
# A simple script to change a directory of one type of images to another.
# Origin  -- Garrett LeSage <garrett@linux.com>
# Mods for Meteor  -- wx273
#########################################################################
#		Yes, this is a hack, but it works pretty well.
#
#		  Note: you probably want to get "tidy" at:
#          http://www.w3.org/People/Raggett/tidy/
#	  (or just "apt-get install tidy" if using Debian)
#########################################################################

# Version of imgconvert
IMGCONVERT_VERSION=0.2

# The file format you wish to change
FROM=png

# The end result file format
TO=png

# Options for "convert"
CONVERT_OPTIONS='-quality 100'

# Pull the directory name for the title
DIR_NAME=`basename $PWD`

# Site name for the title
SITENAME="/"

# This is for the <title> area, and automatically pulls fromt the sitename,
# which can be edited directly above
TOPTITLE="$SITENAME - "

# General title
TITLE="Weather Sat Images captured in Wiltshire, UK"

# Description
DESC="Using Manjaro Linux, wxtoimg-rtl_fm-artlav, Nooelec-smarTEE dongle, NooElec Sawbird NOAA Amp/Filter and homemade QFH antenna "

# Instructions for the viewer
INSTR="Clicking on the thumbnail will download the 640x480 version of 
the image.<br> Both pixel and file sizes are located under each 
picture."

# Page colors, fonts, etc
TEXT="#ffffff"
BGCOLOR="#000000"
LINK="#5555aa"
ALINK="#9999AA"
VLINK="#bbbbee"
FONT_FAMILY="helvetica,arial,sans-serif"

# This credits imgconvert, if you don't want to give credit (for whatever
# reason, I don't know), you can turn it off here. Default is "1". "0" will
# turn off the credit at the bottom.
CREDIT=0

#########################################################################
# The actual convertion stuff
# You can edit stuff below here to change how this works, or just stick
# with the variables above (which should be good for most people
#########################################################################

if [ ! -s "thumb/" ] 
then
	mkdir thumb
fi

if [ ! -s "1024/" ]
then 	
	mkdir 1024
fi

### Header
echo "<html><head><title>$TOPTITLE$TITLE</title><style type=\"text/css\">" > index.html
echo "H1, P {font-family: $FONT_FAMILY}" >> index.html
echo "</style><meta name=\"generator\" content=\"imgconvert $IMGCONVERT_VERSION - http://linuxart.com/imgconvert/\"></head>" >> index.html
echo "<body bgcolor=\"$BGCOLOR\" text=\"$TEXT\"" >> index.html
echo "vlink=\"$VLINK\" link=\"$LINK\">" >> index.html
echo "<h1 align=\"center\">$TITLE</h1>" >> index.html
echo "<p align=\"center\"><b>$DESC</b>" >> index.html
# echo "<p align=\"center\">$PRD" >> index.html
echo "<p align=\"center\">" >> index.html

### End Header
echo "Today's Passes (GMT)" >> index.html
echo "<center><table border=0 align=center><tr><td>" >> index.html
#echo "<center><table border=0 cellspacing=5 cellpadding=7 align=center><tr><td>" >> index.html
#echo "<center><table border=0 cellspacing=5 cellpadding=7 align=center><tr>" >> index.html
echo "<pre><small>" >> index.html
cat /home/user1/Satellite/code/passages.txt | awk '{print $3, $6, $9, $7, $8}' >> index.html
echo "</pre></small>" >> index.html
echo "</td></tr></table>" >> index.html

### Start Pass Prediction Table

HOME="/home/user1"
OUTFILE="index.html"

# Start image matrix

TABLE_START="<center><table border=0 cellspacing=5 cellpadding=7 align=center><tr>"

COUNT=0

for i in `ls -t *.$FROM`;
	do
	j1=`echo $i | awk -F"_" '{print $1}' | sed 's/..$//'`
	j2=`echo $i | awk -F"-" '{print $2}'`
	j3=`echo $i | awk -F"." '{print $1}' | awk -F"_" '{print $2}'`
	COUNTLOOP=`expr $COUNT \% 8`
	
	echo $COUNT   $COUNTLOOP
	if [ $COUNTLOOP -eq 0 ]
	then
		echo "</tr></table></center>$TABLE_START" >> index.html
		echo "4444"
	fi

	COUNT=`expr $COUNT + 1`

	echo "<td>" >> index.html

	CONVERT_OPTIONS='-quality 75 -geometry  156x238'
	_thumb=`basename $i $FROM`thumb.$TO
	if [ ! -s "thumb/$_thumb" ] 
	then
		echo Thumbnailing $i...
		echo      convert $CONVERT_OPTIONS $i $_thumb
		convert $CONVERT_OPTIONS $i thumb/$_thumb
	fi
	
	CONVERT_OPTIONS='-quality 75 -geometry  156x238'
	_1024=`basename $i $FROM`1024.$TO
	if [ ! -s "1024/$_1024" ]
	then
		convert $CONVERT_OPTIONS $i 1024/$_1024
	fi

echo "<p align=\"center\">" >> index.html
echo "<small>$j3</small>" >> index.html
echo "<br>" >> index.html
echo "<small>$j1<small>" >> index.html
echo "<br>" >> index.html
echo "<a href=\"$i\"><img src=\"thumb/$_thumb\"" >> index.html
echo "width=60 height=150 alt=\"$i\"></a><br>" >> index.html
echo "</td>" >> index.html

done;

echo "</td></tr></table>" >> index.html
echo "<p align=\"center\">[<a href=\"http:\/\/satblog.co.uk\">See also Satblog</a>]" >> index.html

#########################################################################
# Tagline at the bottom
# you can turn this off by toggling the "CREDIT" variable at the top
#########################################################################

if [ $CREDIT -eq 1 ]
	then
		echo "<p align=\"center\"><small>Generated by " >> index.html
		echo "<a href=\"http://linuxart.com/imgconvert/\">imgconvert" >> index.html
		echo " $IMGCONVERT_VERSION</a></small>" >> index.html
fi

############################

echo "</body></html>" >> index.html

exit;

